version: 2
jobs:
  build:
    machine: true
    working_directory: ~/eventuate-messaging-kafka-offset-store-elasticsearch
    steps:
      - checkout
      - restore_cache:
          keys:
            - eventuate-messaging-kafka-offset-store-elasticsearch-{{ checksum "gradle.properties" }}
            - eventuate-messaging-kafka-offset-store-elasticsearch-
      - run: TERM=dumb ./gradlew testClasses aggregateJavaDocs
      - save_cache:
          paths:
            - ~/.gradle
          key: eventuate-messaging-kafka-offset-store-elasticsearch-{{ checksum "gradle.properties" }}
      - run: TERM=dumb ./build-and-test-all.sh
      - run:
          name: Publish artifacts
          command: |
            TERM=dumb ./deploy-artifacts.sh
          when: on_success
      - run:
          name: Save JUNIT test results
          command: |
            mkdir -p ~/junit/
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/junit/ \;
          when: always
      - run:
          name: Print container logs
          command: |
            export TERM=dumb
            ./.circleci/print-container-logs.sh
          when: always
      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: ~/junit
      - store_artifacts:
          path: ~/container-logs
