version: 2
jobs:
  build:
    machine: true
    working_directory: ~/eventuate-messaging-kafka-offset-store-elasticsearch
    steps:
      - checkout
      - restore_cache:
          keys:
            - eventuate-messaging-kafka-offset-store-elasticsearch-{{ checksum "gradle.properties" }}
            - eventuate-messaging-kafka-offset-store-elasticsearch-
      - run: TERM=dumb ./gradlew testClasses aggregateJavaDocs
      - save_cache:
          paths:
            - ~/.gradle
          key: eventuate-messaging-kafka-offset-store-elasticsearch-{{ checksum "gradle.properties" }}
      - run: TERM=dumb ./build-and-test-all.sh
      - run:
          name: Publish artifacts
          command: |
            TERM=dumb ./deploy-artifacts.sh
          when: on_success
      - run:
          name: Save test results
          command: |
            mkdir -p ~/junit ~/container-logs
            docker ps -a > ~/container-logs/containers.txt
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/junit/ \;
            sudo bash -c 'find /var/lib/docker/containers -name "*-json.log" -exec cp {} ~/container-logs \;'
            sudo bash -c 'find  ~/container-logs -type f -exec chown circleci {} \;'
          when: always
      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: ~/junit
      - store_artifacts:
          path: ~/container-logs
